### ISSUE TITLE
"interpose" "intersperse"

### ISSUE THREAD

**Issue by justin2004** [abrudz/aplcart#105]
**Suggested additional code entry** 
```
      interpose←{(⊣,⍺,⊢)/⍵}
      ',' interpose 'hithere'
┌─────────────┐
│h,i,t,h,e,r,e│
└─────────────┘
```

Clojure has an [interpose](https://clojuredocs.org/clojure.core/interpose) function.
Haskell calls it [intersperse](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-List.html#v:intersperse).

**Comment by justin2004** [comment]
oh i just noticed that "Join elements of vector Yv with separator Xs" exists with same result.

maybe it just needs to be tagged with these terms?
i kind of like the reduction implementation as well though.

**Comment by abrudz** [comment]
I've added those two keywords.

While the reduction is elegant, it is also hugely inefficient.
