### ISSUE TITLE
Problem with invert permutation

### ISSUE THREAD

**Issue by justin2004** [abrudz/aplcart#108]
Should [this](https://github.com/abrudz/aplcart/blob/48061c5a295f72bc26e92cad1c6b3d43b3fba214/table.tsv#L137) line start with:

```
⍋⍋Jv	Invert permutation
```
instead of
```
⍋Jv	Invert permutation
```
?

Its TIO link makes it look like ⍋⍋ is involved.

**Comment by abrudz** [comment]
No, `⍋` inverts a permutation. For example, at https://www.geeksforgeeks.org/inverse-permutation/ we find the example:
```
Example 2 :
Input  = {2, 3, 4, 5, 1}
Output = {5, 1, 2, 3, 4}
```
And in APL:
```
      ⍋2 3 4 5 1
5 1 2 3 4
```
I've added a comment to the `⍋⍋` line in 02005119d795c49caf060b8b7bafbcbda26dd364
