### ISSUE TITLE
Decimal to Binary conversions

### ISSUE THREAD

**Issue by sloorush** [abrudz/aplcart#115]
**Note**: Other Variations of cases of number system conversion can also be added

**Suggested additional code entry** (required)
```
      11 ⎕dr 2
0 0 0 0 0 0 1 0
```

**Description** (required)
```
Convert a Decimal Number to a Binary Number
```

**Class** (optional)
```
Tacit | Dfn | Dop | Primitive | Syntax | Non-syntax | System | I-beam | Constant | …
```

**Type** (optional)
```
Dyadic Function | Monadic Function | Function | Array | Assignment | Command | Ucmd | …
```

**Group** (optional)
```
Dyadic Operator | Monadic Operator | Structure | Keyword | UCMD GROUP | …
```

**Category** (required)
```
Boolean/Logical | Mathematical
```

**Keywords** (optional)
```
binary number-system decimal
```
**TIO (optional)**
```
https://tio.run/##SyzI0U2pTMzJT////1Hf1EdtEwwNFYCMlCIFo///AQ
```
---
**Note:** By submitting this issue, you permit your contribution to be [used without restriction](../../blob/master/LICENSE).

**Comment by sloorush** [comment]
Maybe this issue can be changed to a general "Add all number system conversions"

**Comment by abrudz** [comment]
There's already an `M(⊥⍣¯1)N` `N in Base M` entry. `11⎕DR` isn't general base conversion, but just returns the bits used internally. This means that the result varies between floats representations (DPD vs BID), and across architectures (little-endian vs big-endian):
```
     2⊥11⎕DR 1000
59395
     2⊥,⊖2 8⍴11⎕DR 1000
1000
```
