### ISSUE TITLE
Odd result in ⍸⍣¯1 search

### ISSUE THREAD

**Issue by bear8642** [abrudz/aplcart#119]
**Is your feature request related to a problem? Please describe.**
Feel "((∪∘.=⊢)⍳⍨)Y	Self-classify: table of unique vs all major cells of Y" odd result for ⍸⍣¯1

**Describe the solution you'd like**
Remove from search result for ⍸⍣¯1

**Describe alternatives you've considered**
Feel should instead be part of results for Key(⌸) as a grouping phrase

**Additional context**
https://aplcart.info/?q=%E2%8D%B8%E2%8D%A3%C2%AF1

**Comment by abrudz** [comment]
It is equivalent to `⍸⍣¯1⍤⊢⌸` and thus will be found for `⌸` too.
