### ISSUE TITLE
Maximum subarray sum

### ISSUE THREAD

**Issue by mlochbaum** [abrudz/aplcart#21]
**Suggested additional code entry** (required)
```
{s←0⋄⌈/{s⊢←0⌈s+⍵}¨⍵}Nv
```

**Description** (required)
```
Largest sum of any contiguous subvector (possibly empty)
```

**Class** (optional)
```
Dfn
```

**Type** (optional)
```
Monadic Function
```

**Group** (optional)
```

```

**Category** (required)
```
Mathematical
```

**Keywords** (optional)
```
maximum subarray largest kadane's algorithm
```

**Comment by abrudz** [comment]
> (possibly empty)

Seems to fail on `⍬`
