### ISSUE TITLE
Please add "2's-complement bitwise arithmetic" and "2's-complement bitwise negation"

### ISSUE THREAD

**Issue by Bubbler-4** [abrudz/aplcart#33]
**Suggested additional code entry** (required)
```
I f{⍉2⊥⍺⍺/{(-⍺⍺0>⍵)⍪⍺⍺2⊥⍣¯1⊢⍵}⍉⍺,[0.5]⍵} J
```

**Description** (required)
```
2's-complement bit-wise application of f between I and J (possibly negative arguments)
```

**Class** (optional)
```
Dop
```

**Type** (optional)
```
Dyadic Function
```

**Group** (optional)
```
Monadic Operator
```

**Category** (required)
```
Boolean/Logical | Mathematical
```

**Keywords** (optional)
```
bit-wise bitwise 2's complement two's complement
```

[Worked example](https://tio.run/##SyzI0U2pTMzJT///qG@qp/@jtgmG/6sf9XYaPepa@qh3FxDpV2voQlgGdo96t2o@6l0F4UKULD603vBR1yKgTC1QG1BYJ9pAzzQWxP@fBjTuUW8fxOSu5kPrjR@1TQTygoOcgWSIh2fwfw0DHZNHvVuMNB91LVEACgJ1KGiATDZQMFQwAEJDTYVHnQvSIIJAuxQMIRKaXERp7VhOttbeTeTbuoJ8WzeSrbVzCRatAA)

If you want to keep the [existing "bitwise" entries](https://aplcart.info/?q=bit-wise#), it'd be good to mention that they assume non-negative arguments.

---

**Suggested additional code entry** (required)
```
¯1∘- J
```

**Description** (required)
```
2's-complement bit-wise negation of J
```

**Class** (optional)
```
Tacit
```

**Type** (optional)
```
Monadic Function
```

**Group** (optional)
```
...
```

**Category** (required)
```
Boolean/Logical | Mathematical
```

**Keywords** (optional)
```
bit-wise bitwise 2's complement two's complement negation negative not
```

---
**Note:** By submitting this issue, you permit your contribution to be [used without restriction](../../blob/master/LICENSE).

**Comment by Bubbler-4** [comment]
A much faster (and slightly shorter) alternative for 2's-complement bitwise dop using `⎕DR`, given that the input arrays are simple arrays of signed 32-bit (or smaller) integers:

```
I f{(⎕DR ⎕DR(⍺⍺⌿11∘⎕DR))⍺,[0.5]⍵} J
```

**Comment by abrudz** [comment]
@Bubbler-4  The original doesn't work with nested arrays. I've not included the `⎕DR`-based entries because it they are a bit to implementation-specific. Feel free to argue otherwise, and I may be persuaded to include them.
