### ISSUE TITLE
Count

### ISSUE THREAD

**Issue by AviFS** [abrudz/aplcart#35]
**Suggested additional code entry** (required)
```
s+.=X
```

**Description** (required)
```
Count occurrences (of s in X)
```

**Class** (optional)
```
(?)
Tacit
```

**Type** (optional)
```
(?)
Dyadic Function
```

**Group** (optional)
```
(?)
Dyadic Operator
```

**Category** (required)
```
(?)
Array Properties
```

**Keywords** (optional)
```
tally occur occurrences
```

---
**Note:** By submitting this issue, you permit your contribution to be [used without restriction](../../blob/master/LICENSE).

**Comment by abrudz** [comment]
[Count occurrences of s in X](https://aplcart.info/?q=Count%20occurrences%20of%20s%20in%20X#)
