### ISSUE TITLE
Trains for mathematical functions on vectors

### ISSUE THREAD

**Issue by RojerGS** [abrudz/aplcart#40]
**Suggested additional code entry**
```
(⊣÷2*∘÷⍨+.×⍨)
```

**Description**
```
Normalize a numerical vector to have length 1
```

**Class**
```
Tacit
```

**Type**
```
Monadic Function
```

**Group** (optional)
```
Dyadic Operator | Monadic Operator | Structure | Keyword | UCMD GROUP | …
```

**Category**
```
Mathematical
```

**Keywords**
```
normalize normalise vector L2 euclidean length norm one 1
```

**TIO**
[https://tio.run/##SyzI0U2pTMzJT///3y@/KFcBDB61TVDQUFAw0nrUMePw9ke9K7T1Dk8HUppcIDWJOZlVqRA1j7oWH96ORRlXdVlqckl@EViVvYLJo94tBgqPulsU8mD6U8BSCONg6oFqHvVNBclhiiBrRoiCnY1VSl1XV1e99tAKhUe9m03//wcA](https://tio.run/##SyzI0U2pTMzJT///3y@/KFcBDB61TVDQUFAw0nrUMePw9ke9K7T1Dk8HUppcIDWJOZlVqRA1j7oWH96ORRlXdVlqckl@EViVvYLJo94tBgqPulsU8mD6U8BSCONg6oFqHvVNBclhiiBrRoiCnY1VSl1XV1e99tAKhUe9m03//wcA)

---

**Suggested additional code entry**
```
(⊢÷+/)
```

**Description**
```
Normalize a numerical vector so that its scalars sum up to 1
```

**Class**
```
Tacit
```

**Type**
```
Monadic Function
```

**Group** (optional)
```
Dyadic Operator | Monadic Operator | Structure | Keyword | UCMD GROUP | …
```

**Category**
```
Mathematical
```

**Keywords**
```
normalize normalise vector sum of components one 1
```

**TIO**

[https://tio.run/##SyzI0U2pTMzJT///3y@/KFcBDB61TVDQUFDQ1tfkAgkm5mRWpUIEH3UtOrwdJM5VXZaaXJJfBBa2VzB51LvFVOFRd4tCHkxDClgKoR@mHqjmUd9UkBymCLJmhCjYYVil1HV1ddVrD61QeNS72fT/fwA](https://tio.run/##SyzI0U2pTMzJT///3y@/KFcBDB61TVDQUFDQ1tfkAgkm5mRWpUIEH3UtOrwdJM5VXZaaXJJfBBa2VzB51LvFVOFRd4tCHkxDClgKoR@mHqjmUd9UkBymCLJmhCjYYVil1HV1ddVrD61QeNS72fT/fwA)

---
**Suggested additional code entry**
```
f {(⊢÷⍺⍺)⍵} Nv
```

**Description**
```
Normalize a numerical vector to have norm given by f equal to 1
```

**Class**
```
Dop
```

**Type** (optional)
```
Dyadic Function | Monadic Function | Function | Array | Assignment | Command | Ucmd | …
```

**Group** (optional)
```
Monadic Operator
```

**Category**
```
Mathematical
```

**Keywords**
```
normalize normalise vector with arbitrary norm
```
**TIO**

[https://tio.run/##SyzI0U2pTMzJT///38fQL78oV@FR2wQFDW39Gk0uHyOEgJHWo44Zh7c/6l2hrXd4OpACSmfmpSEUPOrpAOnhigcJJeZkVqUWgSWqNR51LQJp3AVEmo96t9ZycZWlJpfkQ6QNFQ6tN1IwBpImXFyP@qaCxKAOgaiCCWpARZHM14QpgWs0wqrRiLBGmFfQtcLEsWj@/x8A](https://tio.run/##SyzI0U2pTMzJT///38fQL78oV@FR2wQFDW39Gk0uHyOEgJHWo44Zh7c/6l2hrXd4OpACSmfmpSEUPOrpAOnhigcJJeZkVqUWgSWqNR51LQJp3AVEmo96t9ZycZWlJpfkQ6QNFQ6tN1IwBpImXFyP@qaCxKAOgaiCCWpARZHM14QpgWs0wqrRiLBGmFfQtcLEsWj@/x8A)

---
**Vectors and norms**
In mathematics we define an L-p norm for all p greater than or equal to 1, up to L-infinity. L-1, L-2 and L-infinity are the more common ones and then we talk about the others generally as L-p norms. The first entry in this issue normalizes a vector with respect to the L-2 norm. APL Cart contains an entry for the M-th root of N, which could be used to write the L-p norm of a vector and the L-p normalization.

I didn't include these because maybe they would clutter APL Cart with things that aren't relevant.

(Please note the second submission above is _not_ normalization with respect to the L-1 norm.)

---
**Note:** By submitting this issue, you permit your contribution to be [used without restriction](../../blob/master/LICENSE).

**Comment by abrudz** [comment]
Fixed in 6e7f3865acf2336a1d6a34364f30df8201ebf450
