### ISSUE TITLE
Pascal's triangle snippet

### ISSUE THREAD

**Issue by bruhmese-python** [abrudz/aplcart#89]
**Suggested additional code entry** 
```
pascals←{⍉⌽↑'#'/⍨¨∊(⍳⍵)(1↓⌽⍳⍵)}
```

**Description** (required)
```
Prints the pascals triangle ('character matrix only') for a given integer
```

**Class** (optional)
```
Tacit | Dfn | Dop 
```

**Type** (optional)
```
Function | Array
```

**Category** (required)
```
Array | Expression | Index Generation | Text
```

**Keywords** (optional)
```
pascal Pascal pas triangle
```

**Comment by abrudz** [comment]
Can you give an example of how this is to be used?

**Comment by abrudz** [comment]
Closing this as it isn't clear what's being asked for. Feel free to comment.
